# # VGA


set_property PACKAGE_PIN AC18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]


set_property PACKAGE_PIN W13 [get_ports clrn]
set_property IOSTANDARD LVCMOS18 [get_ports clrn]

set_property PACKAGE_PIN N18 [get_ports ps2_clk]
set_property IOSNANDARD LVCOMS33 [get_ports ps2_clk]
set_property PACKAGE_PIN M19 [get_ports ps2_data]
set_property IOSNANDARD LVCOMS33 [get_ports ps2_data]

 set_property PACKAGE_PIN N21 [get_ports {r[0]}]
set_property PACKAGE_PIN N22 [get_ports {r[1]}]
 set_property PACKAGE_PIN R21 [get_ports {r[2]}]
set_property PACKAGE_PIN P21 [get_ports {r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {r[3]}]
 set_property PACKAGE_PIN R22 [get_ports {g[0]}]
 set_property PACKAGE_PIN R23 [get_ports {g[1]}]
 set_property PACKAGE_PIN T24 [get_ports {g[2]}]
 set_property PACKAGE_PIN T25 [get_ports {g[3]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {g[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {g[3]}]
 set_property PACKAGE_PIN T20 [get_ports {b[0]}]
 set_property PACKAGE_PIN R20 [get_ports {b[1]}]
 set_property PACKAGE_PIN T22 [get_ports {b[2]}]
 set_property PACKAGE_PIN T23 [get_ports {b[3]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
 set_property PACKAGE_PIN M22 [get_ports hs]
 set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property PACKAGE_PIN AA10 [get_ports {btn[0]}]
set_property PACKAGE_PIN AB10 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {btn[1]}]
set_property PACKAGE_PIN AA13 [get_ports {btn[2]}]
set_property PACKAGE_PIN AA12 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {btn[3]}]

set_property PACKAGE_PIN M21 [get_ports vs]
set_property IOSTANDARD LVCMOS33 [get_ports vs]
