# # VGA


set_property PACKAGE_PIN AC18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]


set_property PACKAGE_PIN W13 [get_ports rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]

set_property PACKAGE_PIN N18 [get_ports {ps2_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps2_clk}]
set_property PACKAGE_PIN M19 [get_ports {ps2_data}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps2_data}]


 set_property PACKAGE_PIN N21 [get_ports {r[0]}]
set_property PACKAGE_PIN N22 [get_ports {r[1]}]
 set_property PACKAGE_PIN R21 [get_ports {r[2]}]
set_property PACKAGE_PIN P21 [get_ports {r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {r[3]}]
 set_property PACKAGE_PIN R22 [get_ports {g[0]}]
 set_property PACKAGE_PIN R23 [get_ports {g[1]}]
 set_property PACKAGE_PIN T24 [get_ports {g[2]}]
 set_property PACKAGE_PIN T25 [get_ports {g[3]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {g[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {g[3]}]
 set_property PACKAGE_PIN T20 [get_ports {b[0]}]
 set_property PACKAGE_PIN R20 [get_ports {b[1]}]
 set_property PACKAGE_PIN T22 [get_ports {b[2]}]
 set_property PACKAGE_PIN T23 [get_ports {b[3]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
 set_property PACKAGE_PIN M22 [get_ports hs]
 set_property IOSTANDARD LVCMOS33 [get_ports hs]


set_property PACKAGE_PIN M21 [get_ports vs]
set_property IOSTANDARD LVCMOS33 [get_ports vs]
# Arduino-Segment & AN
set_property PACKAGE_PIN AD21 [get_ports {AN[0]}]
set_property PACKAGE_PIN AC21 [get_ports {AN[1]}]
set_property PACKAGE_PIN AB21 [get_ports {AN[2]}]
set_property PACKAGE_PIN AC22 [get_ports {AN[3]}]
set_property PACKAGE_PIN AB22 [get_ports {SEGMENT[0]}]
set_property PACKAGE_PIN AD24 [get_ports {SEGMENT[1]}]
set_property PACKAGE_PIN AD23 [get_ports {SEGMENT[2]}]
set_property PACKAGE_PIN Y21 [get_ports {SEGMENT[3]}]
set_property PACKAGE_PIN W20 [get_ports {SEGMENT[4]}]
set_property PACKAGE_PIN AC24 [get_ports {SEGMENT[5]}]
set_property PACKAGE_PIN AC23 [get_ports {SEGMENT[6]}]
set_property PACKAGE_PIN AA22 [get_ports {SEGMENT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[7]}]
#set_property PACKAGE_PIN AF25 [get_ports speaker]
   #set_property IOSTANDARD LVCMOS33 [get_ports speaker]
    
    
set_property PACKAGE_PIN AA10 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[0]}]